const STORAGE_KEY = 'milton-bpsc-tracker-v1';
const SUBJECTS = ['Economics','History','Geography','Art & Culture','Polity & Governance','Bihar Special','Polity','International Relations','Essay','General Science','Maths & DI','Environment','Optional History'];

const seed = [
  ['Economics','Paper II - Indian Economy','Framework of an economy and national income accounting'],['Economics','Paper II - Indian Economy','Consumer behaviour, producer behaviour and market forms'],['Economics','Paper II - Indian Economy','Investment, income, employment, distribution and growth'],['Economics','Paper II - Indian Economy','Banking, central banking, credit policy and commercial banks in Bihar'],['Economics','Paper II - Indian Economy','Taxation, budgets, fiscal policy and public finance'],['Economics','Paper II - Indian Economy','International trade, tariffs, exchange rates and balance of payments'],['Economics','Indian Economy','Planned growth, distributive justice and poverty eradication'],['Economics','Indian Economy','Agricultural policy, land reforms and technological change'],['Economics','Indian Economy','Industrial policy, public/private sector and monopolies'],['Economics','Indian Economy','Pricing policy, procurement and public distribution'],['Economics','Indian Economy','Monetary trends, credit policy and financial institutions'],['Economics','Bihar Economy','Agriculture, industry, poverty, unemployment and land reforms in Bihar'],
  ['History','Ancient India','Indus civilisation: origin, cities, trade, decline and continuity'],['History','Ancient India','Vedic age: literature, society, economy, polity and religion'],['History','Ancient India','Jainism, Buddhism, republics and rise of Magadha'],['History','Ancient India','Maurya Empire: administration, society, economy, Ashoka and art'],['History','Ancient India','Post-Maurya dynasties, society, religion, art and Central Asian contacts'],['History','Ancient India','Gupta age and post-Gupta India up to 750 AD'],['History','Medieval India','Rajputs, trade, commerce, art, religion and philosophy'],['History','Medieval India','Cholas, Rashtrakutas, village system and southern culture'],['History','Medieval India','Delhi Sultanate: foundation, Khaljis, Tughluqs and administration'],['History','Medieval India','Bhakti, Sufi movements and cultural interaction'],['History','Medieval India','Vijayanagar Empire: administration, society, economy, art and culture'],['History','Medieval India','Mughal Empire: Akbar, state, revenue, mansabdari and jagirdari'],['History','Medieval India','Aurangzeb, Marathas, regional states and Mughal decline'],['History','Modern India','British conquest, paramountcy and colonial administration'],['History','Modern India','British economic policies, drain of wealth and deindustrialisation'],['History','Modern India','Socio-religious reform, caste movements and tribal revolts'],['History','Modern India','Revolt of 1857, civil rebellions and peasant movements'],['History','Modern India','Indian National Movement: Congress, Gandhian movements and freedom'],['History','Modern India','Partition, Indian National Army and Naval Mutiny of 1946'],['History','World History','Renaissance, Reformation, capitalism and rise of nation states'],['History','World History','American and French Revolutions; liberalism and democracy'],['History','World History','Industrial Revolution, nationalism, imperialism and colonialism'],['History','World History','World Wars, Russian Revolution, China, Japan and global depression'],
  ['Geography','Physical Geography','Geomorphology, plate tectonics, volcanism and landforms'],['Geography','Physical Geography','Atmosphere, air masses, fronts, cyclones and climate classification'],['Geography','Physical Geography','Soils, vegetation, biomes and ecological balance'],['Geography','Physical Geography','Oceans: relief, currents, tides, salinity and coral reefs'],['Geography','Human Geography','Population, migration, cultural regions and demographic transition'],['Geography','Human Geography','Rural and urban settlements, urbanisation and city structure'],['Geography','Economic Geography','Resources, agriculture, industry, energy crisis and world trade'],['Geography','Geography of India','Physiography, drainage, monsoon, soils and vegetation'],['Geography','Geography of India','Resources, conservation, agriculture and green revolution'],['Geography','Geography of India','Industry, transport, trade and regional development'],['Geography','Geography of India','Political geography, boundaries and Indian Ocean geopolitics'],['Geography','Geography of Bihar','Physiographic divisions, soils, forests, climate and agriculture'],['Geography','Geography of Bihar','Floods, droughts, minerals, industries, population and urbanisation'],
  ['Art & Culture','Indian Culture','Mauryan and Pala art and architecture'],['Art & Culture','Indian Culture','Gandhara, Mathura and other post-Mauryan art schools'],['Art & Culture','Indian Culture','Temple, cave, sculpture and painting traditions'],['Art & Culture','Indian Culture','Patna Qalam painting and Bihar folk traditions'],['Art & Culture','Indian Culture','Bhakti, Sufi, Buddhist and Jain cultural traditions'],['Art & Culture','Indian Culture','Indian literature, languages, music, dance and theatre'],
  ['Polity & Governance','Indian Constitution','Constitutional features, Preamble, Fundamental Rights and DPSP'],['Polity & Governance','Union Government','President, Vice-President, Prime Minister, Council of Ministers and Parliament'],['Polity & Governance','Judiciary','Supreme Court, judicial review, PIL and judicial activism'],['Polity & Governance','Federalism','Centre-State relations, Finance Commission and emergency provisions'],['Polity & Governance','Electoral System','Election Commission, elections, representation and political parties'],['Polity & Governance','Local Government','Panchayati Raj, municipalities and 73rd/74th Amendments'],['Polity & Governance','Governance','Transparency, accountability, e-governance, citizen charter and RTI'],
  ['Bihar Special','History of Bihar','Santhal uprising, 1857 in Bihar, Birsa movement and Champaran Satyagraha'],['Bihar Special','Freedom Movement','Quit India Movement, Bihar’s role and national movement leaders'],['Bihar Special','Bihar Administration','Governor, Chief Minister, Council of Ministers and state legislature'],['Bihar Special','Local Government','Panchayati Raj system and local administration in Bihar'],['Bihar Special','Bihar Economy','Agriculture, industries, poverty, unemployment and land reforms'],['Bihar Special','Bihar Geography','Rivers, floods, drought, soils, minerals and industrial regions'],['Bihar Special','Society and Culture','Tribes, languages, festivals, folk art and social development'],
  ['Polity','Political Thought','State, sovereignty, power, authority and legitimacy'],['Polity','Political Institutions','Legislature, executive, judiciary, parties and pressure groups'],['Polity','Political Process','Political socialisation, communication, modernisation and participation'],['Polity','Indian Political System','Colonialism, nationalism and major Indian political thinkers'],['Polity','Indian Political System','Constitution, federalism, Governor and Panchayati Raj in Bihar'],['Polity','Indian Political System','Caste, class, regionalism, secularism and national integration'],
  ['International Relations','International Politics','State system, power, national interest and balance of power'],['International Relations','Theories','Realism, systems theory and decision-making approach'],['International Relations','Foreign Policy','Determinants, imperialism, alliances, isolationism and non-alignment'],['International Relations','Global Order','Cold War, decolonisation, neo-colonialism and Third World'],['International Relations','International Institutions','UN, specialised agencies, international law and ICJ'],['International Relations','Regional Organisations','ASEAN, Arab League, OAU, OAS and European integration'],['International Relations','Security','Arms race, disarmament, nuclear weapons and arms control'],['International Relations','India and the World','India’s neighbours, superpowers, Southeast Asia, Africa and economic diplomacy'],
  ['Essay','Essay Practice','Education, social justice, women and youth'],['Essay','Essay Practice','Democracy, governance, federalism and development'],['Essay','Essay Practice','Economy, agriculture, technology and employment'],['Essay','Essay Practice','Environment, climate change and sustainable development'],['Essay','Essay Practice','Bihar: history, society, culture and future prospects'],
  ['General Science','General Science','Everyday physics: motion, work, energy, heat, light and sound'],['General Science','General Science','Chemistry in daily life: matter, reactions, acids, bases and materials'],['General Science','Biology','Cells, tissues, human systems, nutrition and health'],['General Science','Biology','Genetics, diseases, immunity and biotechnology'],['General Science','Science & Technology','Space, computers, communication, energy and applied technology'],
  ['Maths & DI','Quantitative Aptitude','Number system, simplification, HCF/LCM and percentages'],['Maths & DI','Quantitative Aptitude','Ratio, proportion, averages, profit-loss and simple/compound interest'],['Maths & DI','Quantitative Aptitude','Time-work, time-distance, pipes and cisterns'],['Maths & DI','Data Interpretation','Tables, bar graphs, line graphs and pie charts'],['Maths & DI','Data Interpretation','Data sufficiency, comparison, percentage change and caselets'],
  ['Environment','Environment','Ecosystem, food chain, energy flow and biogeochemical cycles'],['Environment','Environment','Biodiversity, conservation, protected areas and wildlife'],['Environment','Pollution','Air, water, soil, noise pollution and waste management'],['Environment','Climate','Climate change, global warming, ozone depletion and adaptation'],['Environment','Environmental Governance','Environmental laws, EIA, sustainable development and institutions'],
  ['Optional History','Ancient India','Indus, Vedic, pre-Maurya, Maurya, post-Maurya and Gupta periods'],['Optional History','Medieval India','Rajputs, Sultanate, Vijayanagar, Mughals and Marathas'],['Optional History','Modern India','British expansion, colonial policies, reform movements and 1857'],['Optional History','Modern India','National movement, Gandhian era, left movements and independence'],['Optional History','World History','Renaissance, revolutions, industrialisation, imperialism and world wars'],['Optional History','World History','Russian Revolution, China, Japan, nationalism and decolonisation']
];

function newTopic(subject, section, title) { return { id: crypto.randomUUID ? crypto.randomUUID() : String(Date.now()+Math.random()), subject, section, title, status:'not-started', revisionCount:0, revisionDate:'', testDone:false, testMarks:'' }; }
function initialTopics() { return seed.map(x => newTopic(...x)); }
let topics = loadTopics();
function loadTopics(){ try { const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)); return Array.isArray(saved)&&saved.length?saved:initialTopics(); } catch { return initialTopics(); } }
function save(){ localStorage.setItem(STORAGE_KEY,JSON.stringify(topics)); document.getElementById('lastSaved').textContent='Saved just now'; }
function esc(v=''){ return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c])); }
function label(status){ return {'not-started':'Not covered','notes':'Notes done','revised':'Revised / test done','revised-2':'Revised 2–3 times'}[status]||status; }
function statusClass(status){ return status==='revised-2'?'blue':status==='notes'?'yellow':status==='revised'?'green':'red'; }
function fmtDate(v){ if(!v)return 'No revision date'; const d=new Date(v+'T00:00:00'); return d.toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'}); }
function qs(id){return document.getElementById(id)}
function render(){
  const subject=qs('subjectFilter').value, status=qs('statusFilter').value, search=qs('searchInput').value.toLowerCase().trim();
  const filtered=topics.filter(t=>(subject==='all'||t.subject===subject)&&(status==='all'||t.status===status)&&(!search||(t.title+' '+t.subject+' '+t.section).toLowerCase().includes(search)));
  const total=topics.length, counts={green:topics.filter(t=>t.status==='revised').length,yellow:topics.filter(t=>t.status==='notes').length,blue:topics.filter(t=>t.status==='revised-2').length,red:topics.filter(t=>t.status==='not-started').length};
  const covered=total-counts.red, tested=topics.filter(t=>t.testDone).length, marks=topics.filter(t=>t.testMarks!==''&&t.testMarks!==null).map(t=>Number(t.testMarks)).filter(Number.isFinite);
  qs('totalCount').textContent=total;qs('coveredCount').textContent=covered;qs('leftCount').textContent=counts.red;qs('testCount').textContent=tested;qs('averageMarks').textContent=marks.length?(marks.reduce((a,b)=>a+b,0)/marks.length).toFixed(1):'—';
  const pct=total?Math.round(covered/total*100):0;qs('overallPercent').textContent=pct+'%';qs('donutPercent').textContent=pct+'%';
  ['green','yellow','blue','red'].forEach(k=>qs('legend'+k[0].toUpperCase()+k.slice(1)).textContent=counts[k]);
  const deg=k=>total?counts[k]/total*360:0; let a=0; const stops=[]; [['green',deg('green')],['yellow',deg('yellow')],['blue',deg('blue')],['red',deg('red')]].forEach(([k,d])=>{stops.push(`var(--${k}) ${a}deg ${a+d}deg`);a+=d});qs('donut').style.background=`conic-gradient(${stops.join(',')||'var(--red) 0 360deg'})`;
  renderSubjectChart();
  qs('topicsList').innerHTML=filtered.length?filtered.map(t=>`<article class="topic-row" data-status="${t.status}"><div class="status-bar"></div><div><div class="topic-title">${esc(t.title)}</div><div class="topic-meta">${esc(t.section)} · ${t.revisionCount||0} revision${Number(t.revisionCount)===1?'':'s'} · ${t.revisionDate?fmtDate(t.revisionDate):'No revision date'}${t.testDone?' · Test completed':''}${t.testMarks!==''?' · '+esc(t.testMarks)+'/100':''}</div></div><div class="subject-pill">${esc(t.subject)}</div><div class="status-label ${statusClass(t.status)}">${label(t.status)}</div><div class="topic-actions"><button class="small-btn" data-update="${t.id}">Update</button></div></article>`).join(''):'<div class="empty">No matching topics. Add one from the Admin portal.</div>';
  document.querySelectorAll('[data-update]').forEach(b=>b.addEventListener('click',()=>openUpdate(b.dataset.update)));
  renderAdminList();
}
function renderSubjectChart(){ const el=qs('subjectChart'); el.innerHTML=SUBJECTS.map(s=>{const all=topics.filter(t=>t.subject===s),done=all.filter(t=>t.status!=='not-started').length,p=all.length?Math.round(done/all.length*100):0;return all.length?`<div class="bar-row"><span class="bar-label">${esc(s)}</span><span class="bar-track"><span class="bar-fill" style="width:${p}%"></span></span><span class="bar-value">${p}%</span></div>`:''}).join('')||'<div class="empty">Add topics to see the chart.</div>'; }
function renderAdminList(){ qs('adminTopicCount').textContent=topics.length+' topics'; qs('adminTopicList').innerHTML=topics.map(t=>`<div class="admin-topic-item"><div><strong>${esc(t.title)}</strong><small>${esc(t.subject)} · ${esc(t.section)}</small></div><div class="item-actions"><button class="small-btn" data-edit="${t.id}">Edit</button><button class="small-btn danger" data-delete="${t.id}">Delete</button></div></div>`).join('');document.querySelectorAll('[data-edit]').forEach(b=>b.addEventListener('click',()=>fillAdminForm(b.dataset.edit)));document.querySelectorAll('[data-delete]').forEach(b=>b.addEventListener('click',()=>deleteTopic(b.dataset.delete)));}
function populateSubjects(){ const opts=SUBJECTS.map(s=>`<option value="${esc(s)}">${esc(s)}</option>`).join('');qs('subjectFilter').insertAdjacentHTML('beforeend',opts);qs('topicSubject').innerHTML=opts; }
function openUpdate(id){const t=topics.find(x=>x.id===id);if(!t)return;qs('updateId').value=id;qs('updateTitle').textContent=t.title;qs('updateStatus').value=t.status;qs('revisionDate').value=t.revisionDate||'';qs('revisionCount').value=t.revisionCount||0;qs('testDone').checked=!!t.testDone;qs('testMarks').value=t.testMarks??'';qs('updateModal').hidden=false;}
function fillAdminForm(id){const t=topics.find(x=>x.id===id);if(!t)return;qs('topicId').value=id;qs('topicSubject').value=t.subject;qs('topicSection').value=t.section;qs('topicTitle').value=t.title;qs('topicStatus').value=t.status;qs('topicForm').querySelector('button[type=submit]').textContent='Update topic';qs('topicTitle').focus();}
function resetAdmin(){qs('topicForm').reset();qs('topicId').value='';qs('topicForm').querySelector('button[type=submit]').textContent='Save topic';}
function deleteTopic(id){const t=topics.find(x=>x.id===id);if(!t||!confirm('Delete this topic?'))return;topics=topics.filter(x=>x.id!==id);save();render();toast('Topic deleted');}
function toast(msg){const e=qs('toast');e.textContent=msg;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200);}
qs('adminBtn').addEventListener('click',()=>{qs('adminModal').hidden=false;renderAdminList()});qs('closeAdmin').addEventListener('click',()=>qs('adminModal').hidden=true);qs('closeUpdate').addEventListener('click',()=>qs('updateModal').hidden=true);qs('cancelUpdate').addEventListener('click',()=>qs('updateModal').hidden=true);qs('resetForm').addEventListener('click',resetAdmin);['subjectFilter','statusFilter','searchInput'].forEach(id=>qs(id).addEventListener('input',render));
qs('topicForm').addEventListener('submit',e=>{e.preventDefault();const id=qs('topicId').value;const data={subject:qs('topicSubject').value,section:qs('topicSection').value.trim(),title:qs('topicTitle').value.trim(),status:qs('topicStatus').value};if(!data.title)return;if(id){Object.assign(topics.find(t=>t.id===id),data);toast('Topic updated')}else{topics.push(newTopic(data.subject,data.section,data.title));topics[topics.length-1].status=data.status;toast('Topic added')}save();resetAdmin();render();});
qs('updateForm').addEventListener('submit',e=>{e.preventDefault();const t=topics.find(x=>x.id===qs('updateId').value);if(!t)return;Object.assign(t,{status:qs('updateStatus').value,revisionDate:qs('revisionDate').value,revisionCount:Number(qs('revisionCount').value)||0,testDone:qs('testDone').checked,testMarks:qs('testMarks').value});save();qs('updateModal').hidden=true;render();toast('Progress updated');});
qs('exportBtn').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({app:'Milton BPSC Tracker',version:1,exportedAt:new Date().toISOString(),topics},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='milton-bpsc-tracker-backup.json';a.click();URL.revokeObjectURL(a.href);toast('Backup exported');});
qs('importInput').addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);if(!Array.isArray(data.topics))throw Error();topics=data.topics;save();render();toast('Backup imported')}catch{toast('Invalid backup file')}};reader.readAsText(file);e.target.value='';});
populateSubjects();render();
